// pspiechart/src/components/sidebar.tsx
import { Dropdown, DropdownItem } from "../controls/dropdown";
import ObjectTree from "./object-tree";

export default function Sidebar() {
  return (
    <div className="h-full flex flex-col">
      <nav className="bg-moondust dark:bg-night-sky h-11">
        <div className="h-full px-2 flex flex-row justify-between">
          <div className="flex items-center">
            <img src="/PSP-2Color.svg" className="h-7" alt="Logo" />
          </div>
          <div className="flex items-center">
            <Dropdown right name="Create">
              <DropdownItem>Dashboard</DropdownItem>
            </Dropdown>
          </div>
        </div>
      </nav>
      <div className="p-2 flex-1">
        <ObjectTree />
      </div>
    </div>
  );
}

// pspiechart/src/lib/components/Sidebar.svelte
<script>
	import pspColor from '$lib/assets/PSP-2Color-Reversed.svg';
</script>

<div class="d-flex flex-column flex-shrink-0 p-3 bg-dark">
	<a href="/" class="d-flex row align-items-center text-white text-decoration-none">
		<div class="col pe-0">
			<img src={pspColor} class="mb-2" alt="logo" />
		</div>
		<div class="col">
			<h3 class="m-0">Mission Control</h3>
		</div>
	</a>
	<hr />
	<ul class="nav nav-pills flex-column mb-auto">
		<li class="nav-item">
			<a href="#" class="nav-link active text-white" aria-current="page"> Home </a>
		</li>
	</ul>
</div>
